Subs.MimsWeb/Controllers/PromotionController.cs
using Subs.Business;
using Subs.Data;
using Subs.MimsWeb.Models;
using Subs.Presentation;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading;
using System.Web.Mvc;

namespace Subs.MimsWeb.Controllers
{
    public class PromotionController : Controller
    {
        private ProductData gProductData;
        private readonly MIMSDataContext gMIMSDataContext = new MIMSDataContext(Settings.ConnectionString);

        public PromotionController()
        {
            gProductData = new ProductData();
        }

       
        public ActionResult GetProducts(int ProductSelector = (int)WebProductClassifications.All)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.Message = ModelState.ToString();
                    return View("Error");
                }

                WebProducts lWebProducts = new WebProducts();
                lWebProducts.ProductSelector = ProductSelector;
                lWebProducts.Bulletin = NoteData.GetBulletin();
                LoginRequest lLoginRequest = SessionHelper.GetLoginRequest(Session);

                lWebProducts.ListOfWebProducts = gProductData.WebProducts(lWebProducts.ProductSelector);


                if (lWebProducts.ListOfWebProducts.Count() == 0)
                {
                    ViewBag.Message = "Sorry, no product satisfies these requirements";
                    return View("List", lWebProducts);
                }
                else
                {
                    if (lLoginRequest.CustomerId != null)
                    {
                        foreach (WebProduct item in lWebProducts.ListOfWebProducts)
                        {
                            item.Price = SubscriptionBiz.StandardProductPrice(item.ProductId, (int)lLoginRequest.CustomerId);
                        }
                    }

                    // Save this as a session variable, and use it to populate the model.

                    SessionHelper.Set(Session, SessionKey.WebProducts, lWebProducts);

                    return View("List", lWebProducts);   //
                }
            }

            catch (Exception ex)
            {
                //Display all the exceptions

                Exception CurrentException = ex;
                int ExceptionLevel = 0;
                do
                {
                    ExceptionLevel++;
                    ExceptionData.WriteException(1, ExceptionLevel.ToString() + " " + CurrentException.Message, this.ToString(), "GetProducts - post", "");
                    CurrentException = CurrentException.InnerException;
                } while (CurrentException != null);

                ViewBag.Message = ex.Message;

                return View("Error");
            }
        }



        [HttpGet]
        public ViewResult List()
        {

            //Silke insisted that the page where you query what category to select from and the view where you display the products, be the same page.
            //Hence, this view can operate in two modes. The first is just a query, and the second is the query plus the result.

            try
            {

                WebProducts lPreviousSelection = SessionHelper.GetWebProducts(Session);

                //22222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222


                // Add the original prices if the user has logged in in the mean time.

                LoginRequest lLoginRequest = SessionHelper.GetLoginRequest(Session);
                if (lLoginRequest.CustomerId != null && lPreviousSelection.ListOfWebProducts!= null)
                {
                    foreach (WebProduct item in lPreviousSelection.ListOfWebProducts)
                    {
                        item.Price = SubscriptionBiz.StandardProductPrice(item.ProductId, (int)lLoginRequest.CustomerId);
                    }
                }

                return View("List", lPreviousSelection);

                //22222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
            }

            catch (Exception ex)
            {
                //Display all the exceptions

                Exception CurrentException = ex;
                int ExceptionLevel = 0;
                do
                {
                    ExceptionLevel++;
                    ExceptionData.WriteException(1, ExceptionLevel.ToString() + " " + CurrentException.Message, this.ToString(), "List", "");
                    CurrentException = CurrentException.InnerException;
                } while (CurrentException != null);

                ViewBag.Message = ex.Message;

                return View("Error");
            }
        }

      
        public ActionResult GoToBasket()
        {
            if(!SessionHelper.GetLoginRequest(Session).CustomerId.HasValue)
            {
                ViewBag.Message = "You cannot have a basket if you are not logged in first";
                return View("List", (WebProducts)SessionHelper.GetWebProducts(Session));
            }

            Basket lBasket;              
            lBasket = SessionHelper.GetBasket(Session);
           
            //if (lBasket == null)
            //{
            //    ViewBag.Message = "Your basket is empty";
            //    return View("List", (WebProducts)SessionHelper.GetWebProducts(Session));
            //}

            if (lBasket.BasketItems.Count() == 1)
            {
                ViewBag.Message = "There is " + lBasket.BasketItems.Count() + " product selected, resulting in a price of " + lBasket.TotalDiscountedPrice.ToString("R #####0.00");
            }
            else
            {
                ViewBag.Message = "There are " + lBasket.BasketItems.Count() + " products selected, resulting in a price of " + lBasket.TotalDiscountedPrice.ToString("R #####0.00");
            }

            return View("Basket", lBasket);
        }

        public ActionResult AddToBasket(int ProductId)
        {
            string lStage = "GetBasket";

            Basket lBasket = SessionHelper.GetBasket(Session);

            try
            { 
                if (lBasket == null)
                {
                    lBasket = new Basket();
                }

                // If there is one already, add to units per issue

                bool lFound = false;
                foreach (BasketItem item in lBasket.BasketItems)
                {
                    if (item.Subscription.ProductId == ProductId)
                    {
                            lFound = true;
                        item.Subscription.UnitsPerIssue++;
                    }
                }

                lStage = "Found?";

                if (!lFound) 
                {
                    // create a new BasketItem
                    LoginRequest lLoginRequest = SessionHelper.GetLoginRequest(Session);


                    SubscriptionData3 lSubscription = new SubscriptionData3();

                    lSubscription.PayerId = (int)lLoginRequest.CustomerId;
                    lSubscription.ReceiverId = (int)lLoginRequest.CustomerId;
                    lSubscription.ProductId = ProductId;
                    DateTime lNextDate;

                    { 
                        string lResult;
                        if ((lResult = SubscriptionBiz.NextDate((int)lLoginRequest.CustomerId, ProductId, out lNextDate)) != "OK")
                        {
                            ViewBag.Message = lResult;
                            return View("Basket", lBasket);
                        }
                    }

                    {
                        MimsValidationResult lResult = SubscriptionBiz.SetInitialValues(lSubscription, lNextDate);

                        if (lResult.Message != "OK" && !lResult.Prompt) 
                        {
                           ViewBag.Message = lResult.Message;
                           return View("Basket", lBasket);
                        }
                    }

                    BasketItem lBasketItem = new BasketItem() { Subscription = lSubscription };
                    lBasketItem.ProductName = ProductDataStatic.GetProductName(ProductId);
                    lBasket.BasketItems.Add(lBasketItem);
                    
                    lStage = "Calculate";


                    if (SubscriptionBiz.CalculateBasket(lBasket.BasketItems))
                    {
                        lBasket.TotalPrice = 0;
                        lBasket.TotalDiscount = 0;
                        lBasket.TotalDiscountedPrice = 0;


                        foreach (BasketItem item in lBasket.BasketItems)
                        {
                            lBasket.TotalPrice += item.Price;
                            lBasket.TotalDiscount += item.Discount;
                        }

                        lBasket.TotalDiscountedPrice = lBasket.TotalPrice - lBasket.TotalDiscount;

                        if (lBasket.BasketItems.Count() == 1)
                        {
                            ViewBag.Message = "There is " + lBasket.BasketItems.Count() + " product selected, resulting in a price of " + lBasket.TotalDiscountedPrice.ToString("R #####0.00");
                        }
                        else
                        {
                            ViewBag.Message = "There are " + lBasket.BasketItems.Count() + " products selected, resulting in a price of " + lBasket.TotalDiscountedPrice.ToString("R #####0.00");
                        }
                    }

Subs.MimsWeb/Views/Home/About.cshtml
<!DOCTYPE html>
@{
    ViewBag.Title = "About";
}

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mims About Us">
    <meta name="author" content="Mims">
    <title>About Us</title>
    <!-- font icons -->
    <link rel="stylesheet" href="assets/vendors/themify-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/Content/navbar.css" />
    <link rel="stylesheet" href="/Content/Styles.css">

    <!-- Google Tag Manager -->
    <script>
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MRQP4B3F');</script>
    <!-- End Google Tag Manager -->
</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MRQP4B3F"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <!-- Columns start at 50% wide on mobile and bump up to 33.3% wide on desktop -->



    <section id="about" class="section pt-0">
        <div class="container">

            <h6 class="section-title text-center" style="color:dodgerblue">About Us</h6>


            <div class="row align-text-center">
                <div>


                    <p>
                        <span style="font-family:'Sans Serif Collection'; color:dodgerblue; font-size:16px"><b>MIMS</b></span> &ndash; the medical publishing division of Arena Holdings (Pty) Ltd &ndash; is southern Africa&rsquo;s leading publisher of reference information to the medical profession.

                        Our audience includes GPs, specialists, pharmacists, pharmacy assistants, and other healthcare professionals.
                    </p>

                    <p>
                        <span style="font-family:'Sans Serif Collection'; color:dodgerblue; font-size:16px"><b>MIMS</b></span> &ndash; produces a host of publications in the print and digital media.

                        Core products in the print medium include MIMS monthly &ndash; widely regarded as the doctor&rsquo;s most trusted prescription tool &ndash; which consists of abbreviated package insert information on most prescription medicines available in South Africa, and MIMS Desk Reference (MDR) which features both fully detailed and abbreviated medicines listings plus important prescriber information.<br />
                        Providing the healthcare profession with pertinent information on generic medicines, including the SEP and maximum medical aid reimbursement prices, is the quarterly The Generics Dictionary with its accompanying website <strong style="background-color:dodgerblue"><a href="http://www.generic.co.za">www.generic.co.za</a></strong><br />


                        In the veterinary field, we publish IVS quarterly, consisting of abbreviated package insert information on most veterinary medicines available in South Africa, and IVS Desk Reference (IDR) comprising full package insert information.
                    </p>

                    <p>Products in electronic format include the newly relaunched emims &ndash; a standalone, desktop version encompassing MIMS/MDR medicines listings, an ICD10 coding browser, and patient information leaflets on a wide range of medical conditions; and mobiMIMS, comprising MIMS listings for smartphones and Internet-enabled tablet devices. These products can be ordered on their own or in various combinations. Additionally, MIMS publishes ebooks from time to time on topics as diverse as drug usage in sport and medical ethics.</p>

                    <p>Additional publications in the MIMS stable include Guide to OTC Products, The CVS Dictionary and a CPD Handbook series (comprising treatment approaches, drug-class overviews and medicines listings) on such specialist topics as Oncology, Geriatric Medicine, General Medicine and Psychiatry.</p>

                    <p>With over 60 years&rsquo; experience, MIMS is southern Africa&rsquo;s leading publisher of medical reference information for healthcare professionals.</p>
                </div>

            </div>
        </div>
    </section>

    @*End OF About Section*@

</body>
</html>

Subs.MimsWeb/Views/Home/Contact.cshtml
@model Subs.MimsWeb.Models.ContactRequest

@{
    ViewBag.Title = "Contact";
}

<!DOCTYPE html>

<html style="font-family:Arial;">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mims Contact Us">
    <meta name="author" content="Mims">
    <title>Contact Us</title>
    <!-- font icons -->
    <link rel="stylesheet" href="assets/vendors/themify-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/Content/navbar.css" />
    <link rel="stylesheet" href="/Content/Styles.css">
    <!-- Bootstrap + LeadMark main styles -->
    <!-- Google Tag Manager -->
    <script>
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MRQP4B3F');</script>
    <!-- End Google Tag Manager -->
</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MRQP4B3F"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <!--Contact Us-->
    <section id="contact" class="section pt-0">
        <div class="container">
            <h6 class="section-title text-center" style="color:dodgerblue">Contact Us</h6>
            <div class="row align-content-center">
                <div class="col-md-5 my-3">
                    <h3 style=" font-family:'Segoe Print'">Ri&euml;tte van der Merwe</h3>
                    <h6 class="mb-0" style=" font-family:'Segoe Print'"><b>Phone</b></h6>
                    <p class="mb-4">Tel: <a href="tel:0112805856" style="color:black">011 280 5856/9 / 011 280 5533 / 068 022 7581</a></p>

                    <h6 class="mb-0" style="font-family:'Segoe Print'"><b>Address</b></h6>
                    <p class="mb-4"><span style="color:dodgerblue; font-family:'Segoe Print'"><b>Mims</b></span>, a division of Arena Holdings (Pty) Ltd<br />16 Empire Road <br />Parktown <br />Johannesburg <br />2193</p>

                    <h5 class="mb-0" style=" font-family:'Segoe Print'"><b>Email</b></h5>
                    <p class="mb-4"><a href="mailto:vandermerwer@mims.co.za" style="color:black">vandermerwer@mims.co.za</a>&nbsp;</p>

                </div>

                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                <div class="col-md-6" style="padding-top:5em;">
                    <form action="https://formspree.io/f/xleyjeap" method="post">
                        <h4 class="mb-4" style="font-family:'Segoe Print'">Drop a Mail</h4>
                        <div class="form-row">
                            <div class="form-group col-sm-4">
                                <input type="text" class="form-control text-black-50 rounded-0 bg-transparent" name="name" placeholder="Name" required>
                            </div>
                            <div class="form-group col-sm-4">
                                <input type="email" class="form-control text-black-50 rounded-0 bg-transparent" name="Email" placeholder="Email" required>
                            </div>
                            <div class="form-group col-sm-4">
                                <input type="text" class="form-control text-black-50 rounded-0 bg-transparent" name="subject" placeholder="Subject" required>
                            </div>
                            <div class="form-group col-12">
                                <textarea name="message" id="" cols="30" rows="4" class="form-control text-black-50 rounded-0 bg-transparent" placeholder="Message" required></textarea>

                            </div>
                            <div class="form-group col-12 mb-0">
                                <button type="submit" class="btn btn-outline-primary rounded w-md mt-3">Send</button>
                            </div>
                            <br />
                            <div class="form-group col-12">
                                <br />
                                <iframe style="margin-left:1rem" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d4257.766458597883!2d28.038820165392952!3d-26.18559793766059!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x93d86db2d672d7c9!2sTiso+Blackstar!5e0!3m2!1sen!2sza!4v1526976275994" frameborder="0" style="border-style: none; border-color: inherit; border-width: 0; width: 850px; float: right; height: 480px;"></iframe>

                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </section>
    <!--End of Contact-->

</body>
</html>

Subs.MimsWeb/Views/Home/Login.cshtml
@model Subs.MimsWeb.Models.LoginRequest


<!DOCTYPE html>
<html>
<head>


    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">


    <script src="/Scripts/jquery-3.4.1.js"></script>
    <script src="/Scripts/jquery-ui.js"></script>
    <link href="/Content/jquery-ui.css" rel="stylesheet" />
    <script src="/Scripts/Default.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="~/Content/login.css" />
    <link rel="stylesheet" href="/Content/normalise.css">
    <link rel="stylesheet" href="/Content/Styles.css">

    <title>Mims Login</title>
    <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-MRQP4B3F');</script>
    <!-- End Google Tag Manager -->
    <script>
        $(document).ready(function () {
            $('#CustomerLookup').click(function () {
                $('#dialog').dialog("open");
            });

            $('#dialog').dialog({
                modal: true,
                autoOpen: false,
                buttons: [{
                    text: "Go",
                    click: function () {
                        document.getElementById('Email').value = document.getElementById('EmailAddress').value;
                        document.forms["SubmitForm"].submit();
                    }
                }]
            });
        });
    </script>
</head>


<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MRQP4B3F"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <section class="ftco-section">
        <div class="container">

            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6">
                    <div class="login-wrap p-4 p-md-5">

                        @*<h3 class="text-center mb-4">Sign In</h3>*@
                        <div class="MimsImage">
                            <img src="~/Content/img/logos/mims-small.png" width="150" />
                        </div>
                        @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { id = "SubmitForm" }))
                        {
                            <p style="font-family: Arial; margin:2em 0em 2em 1em; color:red;">
                                @Html.ViewBag.Message
                            </p>

                            <p>
                                @Html.CheckBoxFor(x => x.ResetFlag, new { id = "ResetFlag", style = "visibility:hidden" })
                            </p>

                            <p>
                                <input id="Email" name="Email" type="hidden" value="">
                            </p>

                            <div id="dialog">
                                <label>Email address</label>
                                <input type="text" id="EmailAddress" />
                            </div>
                            <div class="form-group text-center">
                                @Html.LabelFor(x => x.CustomerId) &nbsp; &nbsp;
                                @Html.EditorFor(x => x.CustomerId)
                            </div>
                            <div class="form-group  text-center">
                                @Html.LabelFor(x => x.Password) &nbsp;   &nbsp;&nbsp;&nbsp;
                                @Html.EditorFor(x => x.Password)
                            </div>
                            <br />
                            <div class="form-group">
                                <button type="submit" id="signin" class="form-control btn btn-primary rounded submit px-3">Login</button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">

                                    <a href="#" class="LoginStyle" id="CustomerLookup">Forgot customerID</a>

                                </div>

                                <div class="w-50 ">
                                    &nbsp;&nbsp;&nbsp; <a href="~/Home/RegisterEmail">Register</a>
                                </div>

                                <div class="w-50 ">
                                    <a href="#" class="LoginStyle" onclick="ResetPassword()">Forgot password</a>
                                </div>

                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </section>

    <script>
        function UsePassword() {
            try {
                document.getElementById("ResetFlag").checked = false;
                document.forms["SubmitForm"].submit();
            }
            catch (message) {
                alert(message);
            }

        }

        function CustomerLookup() {
            try {

                window.alert("Under construction.");
                // Do an Ajax call to find all customers numbers on this email address, plus their names.

                // Display them in a list where one could be selected.

                //document.getElementById("ResetFlag").checked = false;
                //window.alert("Under construction.");


                //window.alert(document.getElementsByName('Email').values[0]);
                //document.forms["SubmitForm"].submit();

            }
            catch (message) {
                window.alert(message);
            }

        }

        function ResetPassword() {

            try {

                document.getElementById("ResetFlag").checked = true;
                document.forms["SubmitForm"].submit();
            }
            catch (message) {
                window.alert(message);
            }

        }

    </script>

    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="js/main.js"></script>

</body>
</html>

Subs.MimsWeb/Views/Home/Welcome.cshtml

@{
    ViewBag.Title = "Welcome";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="/Content/normalise.css">
    <link rel="stylesheet" href="/Content/Styles.css">
    <link rel="stylesheet" href="~/Content/navbar.css" />
    <title>Welcome</title>
    <!-- Google Tag Manager -->
    <script>
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MRQP4B3F');</script>
    <!-- End Google Tag Manager -->
    <style>
        p {
            padding: 1em 1em 1em 1em;
            font-family: Arial;
            font-size: large;
            font-weight: 600;
            color: blue;
        }
    </style>
</head>
<body style="padding-top:5em;padding-bottom:3em;position:page">
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MRQP4B3F"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <p>
        @Html.ViewBag.Message
    </p>
    <div class="pic">

        <img src="~/Images/WelcomeWide.jpg" style="width:100%; " />

    </div>
    <section id="service" class="section pt-0" style="padding-bottom:1em">
        <div class="container">


            <div class="row">
                <div class="col-md-4">
                    <div class="card mb-5 mb-md-0">
                        <div class="card-body">

                            @*<h5 class="card-title mt-3">SILDENAFIL</h5>*@
                            <p class="mb-0"><a href="~/Promotion/GetProducts"><img src="~/Images/MDR.jpg" class="brands"></a></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-5 mb-md-0">
                        <div class="card-body">

                            @*<h5 class="card-title mt-3">COLLODIAL NASAL SPRAY</h5>*@
                            <p class="mb-0"><a href="~/Promotion/GetProducts"><img src="~/Images/CVS Dictionary 2023.jpg" class="brands"></a></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-5 mb-md-0">
                        <div class="card-body">

                            @*<h5 class="card-title mt-3">COLLODIAL NASAL SPRAY</h5>*@
                            <p class="mb-0"><a href="~/Promotion/GetProducts"><img src="~/Images/IVS Vol61 No2 - 2023.jpg" class="brands"></a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    @*<p>
            @if(Model.Amount > 0.05M)
            {
            @Html.ActionLink("Goto payment menu", "Pay", "Promotion",
            new
                {
                    onclick = "return window.confirm('You have R" + @Model.Amount.ToString("######0.00") + " outstanding on INV" +
                    @Model.InvoiceId.ToString() + " Do you want to pay it now?"
                });
            }
        </p>*@
    @*<footer style="border: solid 1px black; color: #fff; background-color: dodgerblue;
                text-align:center; align-content:center">
            <label>

                <a href="https://sacoronavirus.co.za/" target="_blank" text-decoration:underline; style="color: #fff; background-color: dodgerblue">Online CoronaVirus News</a>
                <label><a href="~/Content/TermsConditions.html" target="_blank" style="font-size:0.9em; color: white;background-color:dodgerblue;">Terms and conditions</a></label>
            </label>
            <br />

            <label style="text-align:center; font-size:0.9em">Copyright &copy; @DateTime.Now.Year  MIMS. All Rights Reserved.</label>



        </footer>*@


</body>
</html>